### ISSUE TITLE
docker-ce-i386 make deb

### ISSUE THREAD

**Issue by NashAqi987p** [mforkel/docker-ce-i386#2]
Hello ,

I'm currently facing issues while compiling Docker CE for an i386 architecture using your `mforkel/docker-ce-i386` repository. I believe your expertise can help me resolve these problems.

The problem I'm encountering happens when I run the `make deb` command as instructed in the repository's README. Here are the errors I'm getting:

yassine@yassine-server:~/docker-ce-i386$ make deb
make VERSION=18.03.0-ce CLI_DIR=/home/yassine/docker-ce-i386/components/cli ENGINE_DIR=/home/yassine/docker-ce-i386/components/engine -C /home/yassine/docker-ce-i386/components/packaging deb
make[1] : on entre dans le répertoire «/h ome/yassine/docker-ce-i386/components/packaging »
for p in ubuntu-xenial ubuntu-trusty debian-buster debian-stretch debian-wheezy debian-jessie raspbian-stretch raspbian-jessie; do \
        make -C deb VERSION=18.03.0-ce ENGINE_DIR=/home/yassine/docker-ce-i386/components/engine CLI_DIR=/home/yassine/docker-ce-i386/components/cli ${p}; \
done
make[2] : on entre dans le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
docker build -t debbuild-ubuntu-xenial/i686 -f /home/yassine/docker-ce-i386/components/packaging/deb/ubuntu-xenial/Dockerfile.i686 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yassine/docker-ce-i386/components/packaging/deb/ubuntu-xenial/Dockerfile.i686: no such file or directory
Makefile:34: recipe for target 'ubuntu-xenial' failed
make[2]: *** [ubuntu-xenial] Error 1
make[2] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
make[2] : on entre dans le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
docker build -t debbuild-ubuntu-trusty/i686 -f /home/yassine/docker-ce-i386/components/packaging/deb/ubuntu-trusty/Dockerfile.i686 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yassine/docker-ce-i386/components/packaging/deb/ubuntu-trusty/Dockerfile.i686: no such file or directory
Makefile:48: recipe for target 'ubuntu-trusty' failed
make[2]: *** [ubuntu-trusty] Error 1
make[2] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
make[2] : on entre dans le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
docker build -t debbuild-debian-buster/i686 -f /home/yassine/docker-ce-i386/components/packaging/deb/debian-buster/Dockerfile.i686 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yassine/docker-ce-i386/components/packaging/deb/debian-buster/Dockerfile.i686: no such file or directory
Makefile:76: recipe for target 'debian-buster' failed
make[2]: *** [debian-buster] Error 1
make[2] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
make[2] : on entre dans le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
docker build -t debbuild-debian-stretch/i686 -f /home/yassine/docker-ce-i386/components/packaging/deb/debian-stretch/Dockerfile.i686 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yassine/docker-ce-i386/components/packaging/deb/debian-stretch/Dockerfile.i686: no such file or directory
Makefile:104: recipe for target 'debian-stretch' failed
make[2]: *** [debian-stretch] Error 1
make[2] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
make[2] : on entre dans le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
docker build -t debbuild-debian-wheezy/i686 -f /home/yassine/docker-ce-i386/components/packaging/deb/debian-wheezy/Dockerfile.i686 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yassine/docker-ce-i386/components/packaging/deb/debian-wheezy/Dockerfile.i686: no such file or directory
Makefile:118: recipe for target 'debian-wheezy' failed
make[2]: *** [debian-wheezy] Error 1
make[2] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
make[2] : on entre dans le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
docker build -t debbuild-debian-jessie/i686 -f /home/yassine/docker-ce-i386/components/packaging/deb/debian-jessie/Dockerfile.i686 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yassine/docker-ce-i386/components/packaging/deb/debian-jessie/Dockerfile.i686: no such file or directory
Makefile:90: recipe for target 'debian-jessie' failed
make[2]: *** [debian-jessie] Error 1
make[2] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
make[2] : on entre dans le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
docker build -t debbuild-raspbian-stretch/i686 -f /home/yassine/docker-ce-i386/components/packaging/deb/raspbian-stretch/Dockerfile.i686 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yassine/docker-ce-i386/components/packaging/deb/raspbian-stretch/Dockerfile.i686: no such file or directory
Makefile:146: recipe for target 'raspbian-stretch' failed
make[2]: *** [raspbian-stretch] Error 1
make[2] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
make[2] : on entre dans le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
docker build -t debbuild-raspbian-jessie/i686 -f /home/yassine/docker-ce-i386/components/packaging/deb/raspbian-jessie/Dockerfile.i686 .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/yassine/docker-ce-i386/components/packaging/deb/raspbian-jessie/Dockerfile.i686: no such file or directory
Makefile:132: recipe for target 'raspbian-jessie' failed
make[2]: *** [raspbian-jessie] Error 1
make[2] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging/deb »
Makefile:27: recipe for target 'deb' failed
make[1]: *** [deb] Error 2
make[1] : on quitte le répertoire « /home/yassine/docker-ce-i386/components/packaging »
Makefile:22: recipe for target 'deb' failed
make: *** [deb] Error 2
I've followed the README instructions carefully and I'm confident I haven't missed a step. Unfortunately, I can't seem to resolve this issue on my own.

I'm currently working on a project that requires Docker CE on an i386 architecture, and your repository seems to be the ideal resource for this task. Any assistance you can provide to resolve these issues would be greatly appreciated.

**Comment by NashAqi987p** [comment]
**1. Start by creating a directory named "/docker-ce-i386" using the "mkdir" command:**

`mkdir ~/docker-ce-i386`

**2. Next, download the "master" branch from this [link](https://github.com/mforkel/docker-ce-i386/tree/master). Click on "Code" and then select "Download ZIP." After the download is complete, extract the contents of the ZIP file into the "/docker-ce-i386" directory.**

**3. Start by deleting the files "cli," "engine," and "packaging" located in the directory "/docker-ce-i386." You can use the "rm" command for this:**


```
sudo rm -r ~/docker-ce-i386/components/cli
sudo rm -r ~/docker-ce-i386/components/engine
sudo rm -r ~/docker-ce-i386/components/packaging
```


**4. Next, ensure you have the "[components.tar](https://mega.nz/file/OAUnWDDa#D27cTwg83u-cYSGV5aX1-_MyCRz6UZmCrgYOgdtc8Ng)" file containing the "cli," "engine," and "packaging" files. Then, extract the contents of this file and copy them to the "/docker-ce-i386/components" directory.**

**5. Navigate to the "~/docker-ce-i386" directory using the "cd" command:**

`cd ~/docker-ce-i386`

**6. Now, execute the following commands to create and install the Docker packages:**

```
sudo make deb
sudo dpkg -i bundles/docker-ce_18.09.0~3-0~ubuntu-bionic_i386.deb
sudo dpkg -i bundles/docker-ce-cli_18.09.0~3-0~ubuntu-bionic_i386.deb
sudo dpkg -i bundles/containerd.io_1.2.6-3_i386.deb

```

**Comment by mforkel** [comment]
Thanks for your report. Could you explain what you did to create the components.tar file?
